# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/newhome/projects/PrimeTV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/newhome/projects/PrimeTV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /scratch/newhome/projects/PrimeTV/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/newhome/projects/PrimeTV/CMakeFiles /scratch/newhome/projects/PrimeTV/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/newhome/projects/PrimeTV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prime

# Build rule for target.
prime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prime
.PHONY : prime

# fast build rule for target.
prime/fast:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/build
.PHONY : prime/fast

#=============================================================================
# Target rules for targets named primetv

# Build rule for target.
primetv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 primetv
.PHONY : primetv

# fast build rule for target.
primetv/fast:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/build
.PHONY : primetv/fast

Color.o: Color.cpp.o
.PHONY : Color.o

# target to build an object file
Color.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Color.cpp.o
.PHONY : Color.cpp.o

Color.i: Color.cpp.i
.PHONY : Color.i

# target to preprocess a source file
Color.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Color.cpp.i
.PHONY : Color.cpp.i

Color.s: Color.cpp.s
.PHONY : Color.s

# target to generate assembly for a file
Color.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Color.cpp.s
.PHONY : Color.cpp.s

Colours.o: Colours.cpp.o
.PHONY : Colours.o

# target to build an object file
Colours.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Colours.cpp.o
.PHONY : Colours.cpp.o

Colours.i: Colours.cpp.i
.PHONY : Colours.i

# target to preprocess a source file
Colours.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Colours.cpp.i
.PHONY : Colours.cpp.i

Colours.s: Colours.cpp.s
.PHONY : Colours.s

# target to generate assembly for a file
Colours.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Colours.cpp.s
.PHONY : Colours.cpp.s

Coord.o: Coord.cc.o
.PHONY : Coord.o

# target to build an object file
Coord.cc.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Coord.cc.o
.PHONY : Coord.cc.o

Coord.i: Coord.cc.i
.PHONY : Coord.i

# target to preprocess a source file
Coord.cc.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Coord.cc.i
.PHONY : Coord.cc.i

Coord.s: Coord.cc.s
.PHONY : Coord.s

# target to generate assembly for a file
Coord.cc.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/Coord.cc.s
.PHONY : Coord.cc.s

DrawTree_time.o: DrawTree_time.cc.o
.PHONY : DrawTree_time.o

# target to build an object file
DrawTree_time.cc.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/DrawTree_time.cc.o
.PHONY : DrawTree_time.cc.o

DrawTree_time.i: DrawTree_time.cc.i
.PHONY : DrawTree_time.i

# target to preprocess a source file
DrawTree_time.cc.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/DrawTree_time.cc.i
.PHONY : DrawTree_time.cc.i

DrawTree_time.s: DrawTree_time.cc.s
.PHONY : DrawTree_time.s

# target to generate assembly for a file
DrawTree_time.cc.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/DrawTree_time.cc.s
.PHONY : DrawTree_time.cc.s

canvas.o: canvas.cpp.o
.PHONY : canvas.o

# target to build an object file
canvas.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/canvas.cpp.o
.PHONY : canvas.cpp.o

canvas.i: canvas.cpp.i
.PHONY : canvas.i

# target to preprocess a source file
canvas.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/canvas.cpp.i
.PHONY : canvas.cpp.i

canvas.s: canvas.cpp.s
.PHONY : canvas.s

# target to generate assembly for a file
canvas.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/canvas.cpp.s
.PHONY : canvas.cpp.s

edge.o: edge.cpp.o
.PHONY : edge.o

# target to build an object file
edge.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/edge.cpp.o
.PHONY : edge.cpp.o

edge.i: edge.cpp.i
.PHONY : edge.i

# target to preprocess a source file
edge.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/edge.cpp.i
.PHONY : edge.cpp.i

edge.s: edge.cpp.s
.PHONY : edge.s

# target to generate assembly for a file
edge.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/edge.cpp.s
.PHONY : edge.cpp.s

layoutrees.o: layoutrees.cpp.o
.PHONY : layoutrees.o

# target to build an object file
layoutrees.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/layoutrees.cpp.o
.PHONY : layoutrees.cpp.o

layoutrees.i: layoutrees.cpp.i
.PHONY : layoutrees.i

# target to preprocess a source file
layoutrees.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/layoutrees.cpp.i
.PHONY : layoutrees.cpp.i

layoutrees.s: layoutrees.cpp.s
.PHONY : layoutrees.s

# target to generate assembly for a file
layoutrees.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/layoutrees.cpp.s
.PHONY : layoutrees.cpp.s

libraries/AnError.o: libraries/AnError.cc.o
.PHONY : libraries/AnError.o

# target to build an object file
libraries/AnError.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/AnError.cc.o
.PHONY : libraries/AnError.cc.o

libraries/AnError.i: libraries/AnError.cc.i
.PHONY : libraries/AnError.i

# target to preprocess a source file
libraries/AnError.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/AnError.cc.i
.PHONY : libraries/AnError.cc.i

libraries/AnError.s: libraries/AnError.cc.s
.PHONY : libraries/AnError.s

# target to generate assembly for a file
libraries/AnError.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/AnError.cc.s
.PHONY : libraries/AnError.cc.s

libraries/NHXannotation.o: libraries/NHXannotation.c.o
.PHONY : libraries/NHXannotation.o

# target to build an object file
libraries/NHXannotation.c.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXannotation.c.o
.PHONY : libraries/NHXannotation.c.o

libraries/NHXannotation.i: libraries/NHXannotation.c.i
.PHONY : libraries/NHXannotation.i

# target to preprocess a source file
libraries/NHXannotation.c.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXannotation.c.i
.PHONY : libraries/NHXannotation.c.i

libraries/NHXannotation.s: libraries/NHXannotation.c.s
.PHONY : libraries/NHXannotation.s

# target to generate assembly for a file
libraries/NHXannotation.c.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXannotation.c.s
.PHONY : libraries/NHXannotation.c.s

libraries/NHXnode.o: libraries/NHXnode.c.o
.PHONY : libraries/NHXnode.o

# target to build an object file
libraries/NHXnode.c.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXnode.c.o
.PHONY : libraries/NHXnode.c.o

libraries/NHXnode.i: libraries/NHXnode.c.i
.PHONY : libraries/NHXnode.i

# target to preprocess a source file
libraries/NHXnode.c.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXnode.c.i
.PHONY : libraries/NHXnode.c.i

libraries/NHXnode.s: libraries/NHXnode.c.s
.PHONY : libraries/NHXnode.s

# target to generate assembly for a file
libraries/NHXnode.c.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXnode.c.s
.PHONY : libraries/NHXnode.c.s

libraries/NHXparse.o: libraries/NHXparse.c.o
.PHONY : libraries/NHXparse.o

# target to build an object file
libraries/NHXparse.c.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXparse.c.o
.PHONY : libraries/NHXparse.c.o

libraries/NHXparse.i: libraries/NHXparse.c.i
.PHONY : libraries/NHXparse.i

# target to preprocess a source file
libraries/NHXparse.c.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXparse.c.i
.PHONY : libraries/NHXparse.c.i

libraries/NHXparse.s: libraries/NHXparse.c.s
.PHONY : libraries/NHXparse.s

# target to generate assembly for a file
libraries/NHXparse.c.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXparse.c.s
.PHONY : libraries/NHXparse.c.s

libraries/NHXtree.o: libraries/NHXtree.c.o
.PHONY : libraries/NHXtree.o

# target to build an object file
libraries/NHXtree.c.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXtree.c.o
.PHONY : libraries/NHXtree.c.o

libraries/NHXtree.i: libraries/NHXtree.c.i
.PHONY : libraries/NHXtree.i

# target to preprocess a source file
libraries/NHXtree.c.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXtree.c.i
.PHONY : libraries/NHXtree.c.i

libraries/NHXtree.s: libraries/NHXtree.c.s
.PHONY : libraries/NHXtree.s

# target to generate assembly for a file
libraries/NHXtree.c.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NHXtree.c.s
.PHONY : libraries/NHXtree.c.s

libraries/Node.o: libraries/Node.cc.o
.PHONY : libraries/Node.o

# target to build an object file
libraries/Node.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/Node.cc.o
.PHONY : libraries/Node.cc.o

libraries/Node.i: libraries/Node.cc.i
.PHONY : libraries/Node.i

# target to preprocess a source file
libraries/Node.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/Node.cc.i
.PHONY : libraries/Node.cc.i

libraries/Node.s: libraries/Node.cc.s
.PHONY : libraries/Node.s

# target to generate assembly for a file
libraries/Node.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/Node.cc.s
.PHONY : libraries/Node.cc.s

libraries/NodeMap.o: libraries/NodeMap.cc.o
.PHONY : libraries/NodeMap.o

# target to build an object file
libraries/NodeMap.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NodeMap.cc.o
.PHONY : libraries/NodeMap.cc.o

libraries/NodeMap.i: libraries/NodeMap.cc.i
.PHONY : libraries/NodeMap.i

# target to preprocess a source file
libraries/NodeMap.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NodeMap.cc.i
.PHONY : libraries/NodeMap.cc.i

libraries/NodeMap.s: libraries/NodeMap.cc.s
.PHONY : libraries/NodeMap.s

# target to generate assembly for a file
libraries/NodeMap.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NodeMap.cc.s
.PHONY : libraries/NodeMap.cc.s

libraries/NodeNodeMap.o: libraries/NodeNodeMap.cc.o
.PHONY : libraries/NodeNodeMap.o

# target to build an object file
libraries/NodeNodeMap.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NodeNodeMap.cc.o
.PHONY : libraries/NodeNodeMap.cc.o

libraries/NodeNodeMap.i: libraries/NodeNodeMap.cc.i
.PHONY : libraries/NodeNodeMap.i

# target to preprocess a source file
libraries/NodeNodeMap.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NodeNodeMap.cc.i
.PHONY : libraries/NodeNodeMap.cc.i

libraries/NodeNodeMap.s: libraries/NodeNodeMap.cc.s
.PHONY : libraries/NodeNodeMap.s

# target to generate assembly for a file
libraries/NodeNodeMap.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/NodeNodeMap.cc.s
.PHONY : libraries/NodeNodeMap.cc.s

libraries/PerturbationObservable.o: libraries/PerturbationObservable.cc.o
.PHONY : libraries/PerturbationObservable.o

# target to build an object file
libraries/PerturbationObservable.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/PerturbationObservable.cc.o
.PHONY : libraries/PerturbationObservable.cc.o

libraries/PerturbationObservable.i: libraries/PerturbationObservable.cc.i
.PHONY : libraries/PerturbationObservable.i

# target to preprocess a source file
libraries/PerturbationObservable.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/PerturbationObservable.cc.i
.PHONY : libraries/PerturbationObservable.cc.i

libraries/PerturbationObservable.s: libraries/PerturbationObservable.cc.s
.PHONY : libraries/PerturbationObservable.s

# target to generate assembly for a file
libraries/PerturbationObservable.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/PerturbationObservable.cc.s
.PHONY : libraries/PerturbationObservable.cc.s

libraries/SetOfNodes.o: libraries/SetOfNodes.cc.o
.PHONY : libraries/SetOfNodes.o

# target to build an object file
libraries/SetOfNodes.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/SetOfNodes.cc.o
.PHONY : libraries/SetOfNodes.cc.o

libraries/SetOfNodes.i: libraries/SetOfNodes.cc.i
.PHONY : libraries/SetOfNodes.i

# target to preprocess a source file
libraries/SetOfNodes.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/SetOfNodes.cc.i
.PHONY : libraries/SetOfNodes.cc.i

libraries/SetOfNodes.s: libraries/SetOfNodes.cc.s
.PHONY : libraries/SetOfNodes.s

# target to generate assembly for a file
libraries/SetOfNodes.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/SetOfNodes.cc.s
.PHONY : libraries/SetOfNodes.cc.s

libraries/StrStrMap.o: libraries/StrStrMap.cc.o
.PHONY : libraries/StrStrMap.o

# target to build an object file
libraries/StrStrMap.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/StrStrMap.cc.o
.PHONY : libraries/StrStrMap.cc.o

libraries/StrStrMap.i: libraries/StrStrMap.cc.i
.PHONY : libraries/StrStrMap.i

# target to preprocess a source file
libraries/StrStrMap.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/StrStrMap.cc.i
.PHONY : libraries/StrStrMap.cc.i

libraries/StrStrMap.s: libraries/StrStrMap.cc.s
.PHONY : libraries/StrStrMap.s

# target to generate assembly for a file
libraries/StrStrMap.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/StrStrMap.cc.s
.PHONY : libraries/StrStrMap.cc.s

libraries/Tree.o: libraries/Tree.cc.o
.PHONY : libraries/Tree.o

# target to build an object file
libraries/Tree.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/Tree.cc.o
.PHONY : libraries/Tree.cc.o

libraries/Tree.i: libraries/Tree.cc.i
.PHONY : libraries/Tree.i

# target to preprocess a source file
libraries/Tree.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/Tree.cc.i
.PHONY : libraries/Tree.cc.i

libraries/Tree.s: libraries/Tree.cc.s
.PHONY : libraries/Tree.s

# target to generate assembly for a file
libraries/Tree.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/Tree.cc.s
.PHONY : libraries/Tree.cc.s

libraries/TreeIO.o: libraries/TreeIO.cc.o
.PHONY : libraries/TreeIO.o

# target to build an object file
libraries/TreeIO.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/TreeIO.cc.o
.PHONY : libraries/TreeIO.cc.o

libraries/TreeIO.i: libraries/TreeIO.cc.i
.PHONY : libraries/TreeIO.i

# target to preprocess a source file
libraries/TreeIO.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/TreeIO.cc.i
.PHONY : libraries/TreeIO.cc.i

libraries/TreeIO.s: libraries/TreeIO.cc.s
.PHONY : libraries/TreeIO.s

# target to generate assembly for a file
libraries/TreeIO.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/TreeIO.cc.s
.PHONY : libraries/TreeIO.cc.s

libraries/TreeIOTraits.o: libraries/TreeIOTraits.cc.o
.PHONY : libraries/TreeIOTraits.o

# target to build an object file
libraries/TreeIOTraits.cc.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/TreeIOTraits.cc.o
.PHONY : libraries/TreeIOTraits.cc.o

libraries/TreeIOTraits.i: libraries/TreeIOTraits.cc.i
.PHONY : libraries/TreeIOTraits.i

# target to preprocess a source file
libraries/TreeIOTraits.cc.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/TreeIOTraits.cc.i
.PHONY : libraries/TreeIOTraits.cc.i

libraries/TreeIOTraits.s: libraries/TreeIOTraits.cc.s
.PHONY : libraries/TreeIOTraits.s

# target to generate assembly for a file
libraries/TreeIOTraits.cc.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/TreeIOTraits.cc.s
.PHONY : libraries/TreeIOTraits.cc.s

libraries/configfile.o: libraries/configfile.cpp.o
.PHONY : libraries/configfile.o

# target to build an object file
libraries/configfile.cpp.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/configfile.cpp.o
.PHONY : libraries/configfile.cpp.o

libraries/configfile.i: libraries/configfile.cpp.i
.PHONY : libraries/configfile.i

# target to preprocess a source file
libraries/configfile.cpp.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/configfile.cpp.i
.PHONY : libraries/configfile.cpp.i

libraries/configfile.s: libraries/configfile.cpp.s
.PHONY : libraries/configfile.s

# target to generate assembly for a file
libraries/configfile.cpp.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/configfile.cpp.s
.PHONY : libraries/configfile.cpp.s

libraries/lexer.o: libraries/lexer.c.o
.PHONY : libraries/lexer.o

# target to build an object file
libraries/lexer.c.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/lexer.c.o
.PHONY : libraries/lexer.c.o

libraries/lexer.i: libraries/lexer.c.i
.PHONY : libraries/lexer.i

# target to preprocess a source file
libraries/lexer.c.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/lexer.c.i
.PHONY : libraries/lexer.c.i

libraries/lexer.s: libraries/lexer.c.s
.PHONY : libraries/lexer.s

# target to generate assembly for a file
libraries/lexer.c.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/lexer.c.s
.PHONY : libraries/lexer.c.s

libraries/treeextended.o: libraries/treeextended.cpp.o
.PHONY : libraries/treeextended.o

# target to build an object file
libraries/treeextended.cpp.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/treeextended.cpp.o
.PHONY : libraries/treeextended.cpp.o

libraries/treeextended.i: libraries/treeextended.cpp.i
.PHONY : libraries/treeextended.i

# target to preprocess a source file
libraries/treeextended.cpp.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/treeextended.cpp.i
.PHONY : libraries/treeextended.cpp.i

libraries/treeextended.s: libraries/treeextended.cpp.s
.PHONY : libraries/treeextended.s

# target to generate assembly for a file
libraries/treeextended.cpp.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/treeextended.cpp.s
.PHONY : libraries/treeextended.cpp.s

libraries/y.tab.o: libraries/y.tab.c.o
.PHONY : libraries/y.tab.o

# target to build an object file
libraries/y.tab.c.o:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/y.tab.c.o
.PHONY : libraries/y.tab.c.o

libraries/y.tab.i: libraries/y.tab.c.i
.PHONY : libraries/y.tab.i

# target to preprocess a source file
libraries/y.tab.c.i:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/y.tab.c.i
.PHONY : libraries/y.tab.c.i

libraries/y.tab.s: libraries/y.tab.c.s
.PHONY : libraries/y.tab.s

# target to generate assembly for a file
libraries/y.tab.c.s:
	$(MAKE) -f CMakeFiles/prime.dir/build.make CMakeFiles/prime.dir/libraries/y.tab.c.s
.PHONY : libraries/y.tab.c.s

mainops.o: mainops.cpp.o
.PHONY : mainops.o

# target to build an object file
mainops.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/mainops.cpp.o
.PHONY : mainops.cpp.o

mainops.i: mainops.cpp.i
.PHONY : mainops.i

# target to preprocess a source file
mainops.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/mainops.cpp.i
.PHONY : mainops.cpp.i

mainops.s: mainops.cpp.s
.PHONY : mainops.s

# target to generate assembly for a file
mainops.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/mainops.cpp.s
.PHONY : mainops.cpp.s

moc_canvas.o: moc_canvas.cxx.o
.PHONY : moc_canvas.o

# target to build an object file
moc_canvas.cxx.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/moc_canvas.cxx.o
.PHONY : moc_canvas.cxx.o

moc_canvas.i: moc_canvas.cxx.i
.PHONY : moc_canvas.i

# target to preprocess a source file
moc_canvas.cxx.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/moc_canvas.cxx.i
.PHONY : moc_canvas.cxx.i

moc_canvas.s: moc_canvas.cxx.s
.PHONY : moc_canvas.s

# target to generate assembly for a file
moc_canvas.cxx.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/moc_canvas.cxx.s
.PHONY : moc_canvas.cxx.s

moc_windows.o: moc_windows.cxx.o
.PHONY : moc_windows.o

# target to build an object file
moc_windows.cxx.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/moc_windows.cxx.o
.PHONY : moc_windows.cxx.o

moc_windows.i: moc_windows.cxx.i
.PHONY : moc_windows.i

# target to preprocess a source file
moc_windows.cxx.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/moc_windows.cxx.i
.PHONY : moc_windows.cxx.i

moc_windows.s: moc_windows.cxx.s
.PHONY : moc_windows.s

# target to generate assembly for a file
moc_windows.cxx.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/moc_windows.cxx.s
.PHONY : moc_windows.cxx.s

parameters.o: parameters.cpp.o
.PHONY : parameters.o

# target to build an object file
parameters.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/parameters.cpp.o
.PHONY : parameters.cpp.o

parameters.i: parameters.cpp.i
.PHONY : parameters.i

# target to preprocess a source file
parameters.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/parameters.cpp.i
.PHONY : parameters.cpp.i

parameters.s: parameters.cpp.s
.PHONY : parameters.s

# target to generate assembly for a file
parameters.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/parameters.cpp.s
.PHONY : parameters.cpp.s

phyltr.o: phyltr.cpp.o
.PHONY : phyltr.o

# target to build an object file
phyltr.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/phyltr.cpp.o
.PHONY : phyltr.cpp.o

phyltr.i: phyltr.cpp.i
.PHONY : phyltr.i

# target to preprocess a source file
phyltr.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/phyltr.cpp.i
.PHONY : phyltr.cpp.i

phyltr.s: phyltr.cpp.s
.PHONY : phyltr.s

# target to generate assembly for a file
phyltr.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/phyltr.cpp.s
.PHONY : phyltr.cpp.s

primetv.o: primetv.cc.o
.PHONY : primetv.o

# target to build an object file
primetv.cc.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/primetv.cc.o
.PHONY : primetv.cc.o

primetv.i: primetv.cc.i
.PHONY : primetv.i

# target to preprocess a source file
primetv.cc.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/primetv.cc.i
.PHONY : primetv.cc.i

primetv.s: primetv.cc.s
.PHONY : primetv.s

# target to generate assembly for a file
primetv.cc.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/primetv.cc.s
.PHONY : primetv.cc.s

qrc_application.o: qrc_application.cxx.o
.PHONY : qrc_application.o

# target to build an object file
qrc_application.cxx.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/qrc_application.cxx.o
.PHONY : qrc_application.cxx.o

qrc_application.i: qrc_application.cxx.i
.PHONY : qrc_application.i

# target to preprocess a source file
qrc_application.cxx.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/qrc_application.cxx.i
.PHONY : qrc_application.cxx.i

qrc_application.s: qrc_application.cxx.s
.PHONY : qrc_application.s

# target to generate assembly for a file
qrc_application.cxx.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/qrc_application.cxx.s
.PHONY : qrc_application.cxx.s

windows.o: windows.cpp.o
.PHONY : windows.o

# target to build an object file
windows.cpp.o:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/windows.cpp.o
.PHONY : windows.cpp.o

windows.i: windows.cpp.i
.PHONY : windows.i

# target to preprocess a source file
windows.cpp.i:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/windows.cpp.i
.PHONY : windows.cpp.i

windows.s: windows.cpp.s
.PHONY : windows.s

# target to generate assembly for a file
windows.cpp.s:
	$(MAKE) -f CMakeFiles/primetv.dir/build.make CMakeFiles/primetv.dir/windows.cpp.s
.PHONY : windows.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... prime"
	@echo "... primetv"
	@echo "... rebuild_cache"
	@echo "... Color.o"
	@echo "... Color.i"
	@echo "... Color.s"
	@echo "... Colours.o"
	@echo "... Colours.i"
	@echo "... Colours.s"
	@echo "... Coord.o"
	@echo "... Coord.i"
	@echo "... Coord.s"
	@echo "... DrawTree_time.o"
	@echo "... DrawTree_time.i"
	@echo "... DrawTree_time.s"
	@echo "... canvas.o"
	@echo "... canvas.i"
	@echo "... canvas.s"
	@echo "... edge.o"
	@echo "... edge.i"
	@echo "... edge.s"
	@echo "... layoutrees.o"
	@echo "... layoutrees.i"
	@echo "... layoutrees.s"
	@echo "... libraries/AnError.o"
	@echo "... libraries/AnError.i"
	@echo "... libraries/AnError.s"
	@echo "... libraries/NHXannotation.o"
	@echo "... libraries/NHXannotation.i"
	@echo "... libraries/NHXannotation.s"
	@echo "... libraries/NHXnode.o"
	@echo "... libraries/NHXnode.i"
	@echo "... libraries/NHXnode.s"
	@echo "... libraries/NHXparse.o"
	@echo "... libraries/NHXparse.i"
	@echo "... libraries/NHXparse.s"
	@echo "... libraries/NHXtree.o"
	@echo "... libraries/NHXtree.i"
	@echo "... libraries/NHXtree.s"
	@echo "... libraries/Node.o"
	@echo "... libraries/Node.i"
	@echo "... libraries/Node.s"
	@echo "... libraries/NodeMap.o"
	@echo "... libraries/NodeMap.i"
	@echo "... libraries/NodeMap.s"
	@echo "... libraries/NodeNodeMap.o"
	@echo "... libraries/NodeNodeMap.i"
	@echo "... libraries/NodeNodeMap.s"
	@echo "... libraries/PerturbationObservable.o"
	@echo "... libraries/PerturbationObservable.i"
	@echo "... libraries/PerturbationObservable.s"
	@echo "... libraries/SetOfNodes.o"
	@echo "... libraries/SetOfNodes.i"
	@echo "... libraries/SetOfNodes.s"
	@echo "... libraries/StrStrMap.o"
	@echo "... libraries/StrStrMap.i"
	@echo "... libraries/StrStrMap.s"
	@echo "... libraries/Tree.o"
	@echo "... libraries/Tree.i"
	@echo "... libraries/Tree.s"
	@echo "... libraries/TreeIO.o"
	@echo "... libraries/TreeIO.i"
	@echo "... libraries/TreeIO.s"
	@echo "... libraries/TreeIOTraits.o"
	@echo "... libraries/TreeIOTraits.i"
	@echo "... libraries/TreeIOTraits.s"
	@echo "... libraries/configfile.o"
	@echo "... libraries/configfile.i"
	@echo "... libraries/configfile.s"
	@echo "... libraries/lexer.o"
	@echo "... libraries/lexer.i"
	@echo "... libraries/lexer.s"
	@echo "... libraries/treeextended.o"
	@echo "... libraries/treeextended.i"
	@echo "... libraries/treeextended.s"
	@echo "... libraries/y.tab.o"
	@echo "... libraries/y.tab.i"
	@echo "... libraries/y.tab.s"
	@echo "... mainops.o"
	@echo "... mainops.i"
	@echo "... mainops.s"
	@echo "... moc_canvas.o"
	@echo "... moc_canvas.i"
	@echo "... moc_canvas.s"
	@echo "... moc_windows.o"
	@echo "... moc_windows.i"
	@echo "... moc_windows.s"
	@echo "... parameters.o"
	@echo "... parameters.i"
	@echo "... parameters.s"
	@echo "... phyltr.o"
	@echo "... phyltr.i"
	@echo "... phyltr.s"
	@echo "... primetv.o"
	@echo "... primetv.i"
	@echo "... primetv.s"
	@echo "... qrc_application.o"
	@echo "... qrc_application.i"
	@echo "... qrc_application.s"
	@echo "... windows.o"
	@echo "... windows.i"
	@echo "... windows.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

